language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x

services:
  - mysql

# create test database
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS users;'
  - export MYSQL_TEST_DSN="travis:@/users?parseTime=true"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=585ec926ed59ac42f162c9b3efdac56509113616a4681f256d3313845bf9a11c