// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/ie310mu/ie310go/forks/github.com/golang/protobuf/proto"
	grpc "github.com/ie310mu/ie310go/forks/google.golang.org/grpc"
	codes "github.com/ie310mu/ie310go/forks/google.golang.org/grpc/codes"
	status "github.com/ie310mu/ie310go/forks/google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcRequest struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcRequest) Reset()         { *m = GrpcRequest{} }
func (m *GrpcRequest) String() string { return proto.CompactTextString(m) }
func (*GrpcRequest) ProtoMessage()    {}
func (*GrpcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *GrpcRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcRequest.Unmarshal(m, b)
}
func (m *GrpcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcRequest.Marshal(b, m, deterministic)
}
func (m *GrpcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcRequest.Merge(m, src)
}
func (m *GrpcRequest) XXX_Size() int {
	return xxx_messageInfo_GrpcRequest.Size(m)
}
func (m *GrpcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcRequest proto.InternalMessageInfo

func (m *GrpcRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GrpcResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcResponse) Reset()         { *m = GrpcResponse{} }
func (m *GrpcResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcResponse) ProtoMessage()    {}
func (*GrpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *GrpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcResponse.Unmarshal(m, b)
}
func (m *GrpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcResponse.Marshal(b, m, deterministic)
}
func (m *GrpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcResponse.Merge(m, src)
}
func (m *GrpcResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcResponse.Size(m)
}
func (m *GrpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcResponse proto.InternalMessageInfo

func (m *GrpcResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*GrpcRequest)(nil), "GrpcRequest")
	proto.RegisterType((*GrpcResponse)(nil), "GrpcResponse")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe4, 0xe2, 0x76, 0x2f, 0x2a, 0x48, 0x0e, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb8, 0x78, 0x20, 0x4a, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0xb1, 0xa9, 0x31, 0xb2, 0xe4, 0xe2, 0xf3, 0x4c, 0x35, 0x36, 0x34, 0x70, 0xcf, 0x0f,
	0x4e, 0x2d, 0x2a, 0x4b, 0xce, 0x4c, 0x15, 0x52, 0xe7, 0x62, 0xf3, 0xcc, 0x2b, 0xcb, 0xcf, 0x4e,
	0x15, 0xe2, 0xd1, 0x43, 0xb2, 0x41, 0x8a, 0x57, 0x0f, 0xd9, 0x30, 0x25, 0x86, 0x24, 0x36, 0xb0,
	0x43, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x43, 0x60, 0xfe, 0x96, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Ie310GoServcieClient is the client API for Ie310GoServcie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/github.com/ie310mu/ie310go/forks/google.golang.org/grpc#ClientConn.NewStream.
type Ie310GoServcieClient interface {
	Invoke(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error)
}

type ie310GoServcieClient struct {
	cc *grpc.ClientConn
}

func NewIe310GoServcieClient(cc *grpc.ClientConn) Ie310GoServcieClient {
	return &ie310GoServcieClient{cc}
}

func (c *ie310GoServcieClient) Invoke(ctx context.Context, in *GrpcRequest, opts ...grpc.CallOption) (*GrpcResponse, error) {
	out := new(GrpcResponse)
	err := c.cc.Invoke(ctx, "/Ie310GoServcie/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ie310GoServcieServer is the server API for Ie310GoServcie service.
type Ie310GoServcieServer interface {
	Invoke(context.Context, *GrpcRequest) (*GrpcResponse, error)
}

// UnimplementedIe310GoServcieServer can be embedded to have forward compatible implementations.
type UnimplementedIe310GoServcieServer struct {
}

func (*UnimplementedIe310GoServcieServer) Invoke(ctx context.Context, req *GrpcRequest) (*GrpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterIe310GoServcieServer(s *grpc.Server, srv Ie310GoServcieServer) {
	s.RegisterService(&_Ie310GoServcie_serviceDesc, srv)
}

func _Ie310GoServcie_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ie310GoServcieServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ie310GoServcie/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ie310GoServcieServer).Invoke(ctx, req.(*GrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ie310GoServcie_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ie310GoServcie",
	HandlerType: (*Ie310GoServcieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Ie310GoServcie_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
