
# Gopkg.toml example
#
# Refer to https://github.com/ie310mu/ie310go/forks/github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/ie310mu/ie310go/forks/github.com/user/thing/cmd/thing"]
# ignored = ["github.com/ie310mu/ie310go/forks/github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/ie310mu/ie310go/forks/github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/ie310mu/ie310go/forks/github.com/user/project2"
#   branch = "dev"
#   source = "github.com/ie310mu/ie310go/forks/github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/ie310mu/ie310go/forks/github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/edsrzf/mmap-go"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/glendc/gopher-json"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/pelletier/go-toml"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/peterh/liner"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/siddontang/go"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/siddontang/goredis"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/siddontang/rdb"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/syndtr/goleveldb"
  revision = "cfa635847112c5dc4782e128fa7e0d05fdbfb394"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/ugorji/go"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/github.com/yuin/gopher-lua"

[[constraint]]
  name = "github.com/ie310mu/ie310go/forks/golang.org/x/net"
