language: go
go_import_path: github.com/ie310mu/ie310go/forks/go.etcd.io/bbolt

sudo: false

go:
- 1.11

before_install:
- go get -v honnef.co/go/tools/...
- go get -v github.com/kisielk/errcheck

script:
- make fmt
- make test
- make race
# - make errcheck
