language: go

go_import_path: github.com/go-ego/murmur

go:
  # - 1.7.x
  # - 1.8.x
  # - 1.9.x
  # - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -t ./...
